// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file EmergencyMSGTypeObjectSupport.cxx
 * Source file containing the implementation to register the TypeObject representation of the described types in the IDL file
 *
 * This file was generated by the tool fastddsgen (version: 4.2.0).
 */

#include "EmergencyMSGTypeObjectSupport.hpp"

#include <mutex>
#include <string>

#include <fastcdr/xcdr/external.hpp>
#include <fastcdr/xcdr/optional.hpp>
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/dds/log/Log.hpp>
#include <fastdds/dds/xtypes/common.hpp>
#include <fastdds/dds/xtypes/type_representation/ITypeObjectRegistry.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObject.hpp>
#include <fastdds/dds/xtypes/type_representation/TypeObjectUtils.hpp>
#include "EmergencyMSG.hpp"


using namespace eprosima::fastdds::dds::xtypes;

// TypeIdentifier is returned by reference: dependent structures/unions are registered in this same method
void register_EmergencyMSG_type_identifier(
        TypeIdentifierPair& type_ids_EmergencyMSG)
{

    ReturnCode_t return_code_EmergencyMSG {eprosima::fastdds::dds::RETCODE_OK};
    return_code_EmergencyMSG =
        eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
        "EmergencyMSG", type_ids_EmergencyMSG);
    if (eprosima::fastdds::dds::RETCODE_OK != return_code_EmergencyMSG)
    {
        StructTypeFlag struct_flags_EmergencyMSG = TypeObjectUtils::build_struct_type_flag(eprosima::fastdds::dds::xtypes::ExtensibilityKind::APPENDABLE,
                false, false);
        QualifiedTypeName type_name_EmergencyMSG = "EmergencyMSG";
        eprosima::fastcdr::optional<AppliedBuiltinTypeAnnotations> type_ann_builtin_EmergencyMSG;
        eprosima::fastcdr::optional<AppliedAnnotationSeq> ann_custom_EmergencyMSG;
        AppliedAnnotationSeq tmp_ann_custom_EmergencyMSG;
        eprosima::fastcdr::optional<AppliedVerbatimAnnotation> verbatim_EmergencyMSG;
        if (!tmp_ann_custom_EmergencyMSG.empty())
        {
            ann_custom_EmergencyMSG = tmp_ann_custom_EmergencyMSG;
        }

        CompleteTypeDetail detail_EmergencyMSG = TypeObjectUtils::build_complete_type_detail(type_ann_builtin_EmergencyMSG, ann_custom_EmergencyMSG, type_name_EmergencyMSG.to_string());
        CompleteStructHeader header_EmergencyMSG;
        header_EmergencyMSG = TypeObjectUtils::build_complete_struct_header(TypeIdentifier(), detail_EmergencyMSG);
        CompleteStructMemberSeq member_seq_EmergencyMSG;
        {
            TypeIdentifierPair type_ids_sender_id;
            ReturnCode_t return_code_sender_id {eprosima::fastdds::dds::RETCODE_OK};
            return_code_sender_id =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "anonymous_string_unbounded", type_ids_sender_id);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_sender_id)
            {
                {
                    SBound bound = 0;
                    StringSTypeDefn string_sdefn = TypeObjectUtils::build_string_s_type_defn(bound);
                    if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                            TypeObjectUtils::build_and_register_s_string_type_identifier(string_sdefn,
                            "anonymous_string_unbounded", type_ids_sender_id))
                    {
                        EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                            "anonymous_string_unbounded already registered in TypeObjectRegistry for a different type.");
                    }
                }
            }
            StructMemberFlag member_flags_sender_id = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_sender_id = 0x00000000;
            bool common_sender_id_ec {false};
            CommonStructMember common_sender_id {TypeObjectUtils::build_common_struct_member(member_id_sender_id, member_flags_sender_id, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_sender_id, common_sender_id_ec))};
            if (!common_sender_id_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure sender_id member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_sender_id = "sender_id";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_sender_id;
            ann_custom_EmergencyMSG.reset();
            CompleteMemberDetail detail_sender_id = TypeObjectUtils::build_complete_member_detail(name_sender_id, member_ann_builtin_sender_id, ann_custom_EmergencyMSG);
            CompleteStructMember member_sender_id = TypeObjectUtils::build_complete_struct_member(common_sender_id, detail_sender_id);
            TypeObjectUtils::add_complete_struct_member(member_seq_EmergencyMSG, member_sender_id);
        }
        {
            TypeIdentifierPair type_ids_origin;
            ReturnCode_t return_code_origin {eprosima::fastdds::dds::RETCODE_OK};
            return_code_origin =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_byte", type_ids_origin);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_origin)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "origin Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_origin = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_origin = 0x00000001;
            bool common_origin_ec {false};
            CommonStructMember common_origin {TypeObjectUtils::build_common_struct_member(member_id_origin, member_flags_origin, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_origin, common_origin_ec))};
            if (!common_origin_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure origin member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_origin = "origin";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_origin;
            ann_custom_EmergencyMSG.reset();
            CompleteMemberDetail detail_origin = TypeObjectUtils::build_complete_member_detail(name_origin, member_ann_builtin_origin, ann_custom_EmergencyMSG);
            CompleteStructMember member_origin = TypeObjectUtils::build_complete_struct_member(common_origin, detail_origin);
            TypeObjectUtils::add_complete_struct_member(member_seq_EmergencyMSG, member_origin);
        }
        {
            TypeIdentifierPair type_ids_destination;
            ReturnCode_t return_code_destination {eprosima::fastdds::dds::RETCODE_OK};
            return_code_destination =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_byte", type_ids_destination);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_destination)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "destination Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_destination = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_destination = 0x00000002;
            bool common_destination_ec {false};
            CommonStructMember common_destination {TypeObjectUtils::build_common_struct_member(member_id_destination, member_flags_destination, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_destination, common_destination_ec))};
            if (!common_destination_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure destination member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_destination = "destination";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_destination;
            ann_custom_EmergencyMSG.reset();
            CompleteMemberDetail detail_destination = TypeObjectUtils::build_complete_member_detail(name_destination, member_ann_builtin_destination, ann_custom_EmergencyMSG);
            CompleteStructMember member_destination = TypeObjectUtils::build_complete_struct_member(common_destination, detail_destination);
            TypeObjectUtils::add_complete_struct_member(member_seq_EmergencyMSG, member_destination);
        }
        {
            TypeIdentifierPair type_ids_priority_level;
            ReturnCode_t return_code_priority_level {eprosima::fastdds::dds::RETCODE_OK};
            return_code_priority_level =
                eprosima::fastdds::dds::DomainParticipantFactory::get_instance()->type_object_registry().get_type_identifiers(
                "_byte", type_ids_priority_level);

            if (eprosima::fastdds::dds::RETCODE_OK != return_code_priority_level)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                        "priority_level Structure member TypeIdentifier unknown to TypeObjectRegistry.");
                return;
            }
            StructMemberFlag member_flags_priority_level = TypeObjectUtils::build_struct_member_flag(eprosima::fastdds::dds::xtypes::TryConstructFailAction::DISCARD,
                    false, false, false, false);
            MemberId member_id_priority_level = 0x00000003;
            bool common_priority_level_ec {false};
            CommonStructMember common_priority_level {TypeObjectUtils::build_common_struct_member(member_id_priority_level, member_flags_priority_level, TypeObjectUtils::retrieve_complete_type_identifier(type_ids_priority_level, common_priority_level_ec))};
            if (!common_priority_level_ec)
            {
                EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION, "Structure priority_level member TypeIdentifier inconsistent.");
                return;
            }
            MemberName name_priority_level = "priority_level";
            eprosima::fastcdr::optional<AppliedBuiltinMemberAnnotations> member_ann_builtin_priority_level;
            ann_custom_EmergencyMSG.reset();
            CompleteMemberDetail detail_priority_level = TypeObjectUtils::build_complete_member_detail(name_priority_level, member_ann_builtin_priority_level, ann_custom_EmergencyMSG);
            CompleteStructMember member_priority_level = TypeObjectUtils::build_complete_struct_member(common_priority_level, detail_priority_level);
            TypeObjectUtils::add_complete_struct_member(member_seq_EmergencyMSG, member_priority_level);
        }
        CompleteStructType struct_type_EmergencyMSG = TypeObjectUtils::build_complete_struct_type(struct_flags_EmergencyMSG, header_EmergencyMSG, member_seq_EmergencyMSG);
        if (eprosima::fastdds::dds::RETCODE_BAD_PARAMETER ==
                TypeObjectUtils::build_and_register_struct_type_object(struct_type_EmergencyMSG, type_name_EmergencyMSG.to_string(), type_ids_EmergencyMSG))
        {
            EPROSIMA_LOG_ERROR(XTYPES_TYPE_REPRESENTATION,
                    "EmergencyMSG already registered in TypeObjectRegistry for a different type.");
        }
    }
}
