// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file EmergencyMSG.hpp
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool fastddsgen (version: 4.2.0).
 */

#ifndef FAST_DDS_GENERATED__EMERGENCYMSG_HPP
#define FAST_DDS_GENERATED__EMERGENCYMSG_HPP

#include <cstdint>
#include <string>
#include <utility>
#include <fastcdr/cdr/fixed_size_string.hpp>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define eProsima_user_DllExport
#endif  // _WIN32

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(EMERGENCYMSG_SOURCE)
#define EMERGENCYMSG_DllAPI __declspec( dllexport )
#else
#define EMERGENCYMSG_DllAPI __declspec( dllimport )
#endif // EMERGENCYMSG_SOURCE
#else
#define EMERGENCYMSG_DllAPI
#endif  // EPROSIMA_USER_DLL_EXPORT
#else
#define EMERGENCYMSG_DllAPI
#endif // _WIN32

/*!
 * @brief This class represents the structure EmergencyMSG defined by the user in the IDL file.
 * @ingroup EmergencyMSG
 */
class EmergencyMSG
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport EmergencyMSG()
    {
    }

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~EmergencyMSG()
    {
    }

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object EmergencyMSG that will be copied.
     */
    eProsima_user_DllExport EmergencyMSG(
            const EmergencyMSG& x)
    {
                    m_sender_id = x.m_sender_id;

                    m_origin = x.m_origin;

                    m_destination = x.m_destination;

    }

    /*!
     * @brief Move constructor.
     * @param x Reference to the object EmergencyMSG that will be copied.
     */
    eProsima_user_DllExport EmergencyMSG(
            EmergencyMSG&& x) noexcept
    {
        m_sender_id = std::move(x.m_sender_id);
        m_origin = x.m_origin;
        m_destination = x.m_destination;
    }

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object EmergencyMSG that will be copied.
     */
    eProsima_user_DllExport EmergencyMSG& operator =(
            const EmergencyMSG& x)
    {

                    m_sender_id = x.m_sender_id;

                    m_origin = x.m_origin;

                    m_destination = x.m_destination;

        return *this;
    }

    /*!
     * @brief Move assignment.
     * @param x Reference to the object EmergencyMSG that will be copied.
     */
    eProsima_user_DllExport EmergencyMSG& operator =(
            EmergencyMSG&& x) noexcept
    {

        m_sender_id = std::move(x.m_sender_id);
        m_origin = x.m_origin;
        m_destination = x.m_destination;
        return *this;
    }

    /*!
     * @brief Comparison operator.
     * @param x EmergencyMSG object to compare.
     */
    eProsima_user_DllExport bool operator ==(
            const EmergencyMSG& x) const
    {
        return (m_sender_id == x.m_sender_id &&
           m_origin == x.m_origin &&
           m_destination == x.m_destination);
    }

    /*!
     * @brief Comparison operator.
     * @param x EmergencyMSG object to compare.
     */
    eProsima_user_DllExport bool operator !=(
            const EmergencyMSG& x) const
    {
        return !(*this == x);
    }

    /*!
     * @brief This function copies the value in member sender_id
     * @param _sender_id New value to be copied in member sender_id
     */
    eProsima_user_DllExport void sender_id(
            const std::string& _sender_id)
    {
        m_sender_id = _sender_id;
    }

    /*!
     * @brief This function moves the value in member sender_id
     * @param _sender_id New value to be moved in member sender_id
     */
    eProsima_user_DllExport void sender_id(
            std::string&& _sender_id)
    {
        m_sender_id = std::move(_sender_id);
    }

    /*!
     * @brief This function returns a constant reference to member sender_id
     * @return Constant reference to member sender_id
     */
    eProsima_user_DllExport const std::string& sender_id() const
    {
        return m_sender_id;
    }

    /*!
     * @brief This function returns a reference to member sender_id
     * @return Reference to member sender_id
     */
    eProsima_user_DllExport std::string& sender_id()
    {
        return m_sender_id;
    }


    /*!
     * @brief This function sets a value in member origin
     * @param _origin New value for member origin
     */
    eProsima_user_DllExport void origin(
            uint8_t _origin)
    {
        m_origin = _origin;
    }

    /*!
     * @brief This function returns the value of member origin
     * @return Value of member origin
     */
    eProsima_user_DllExport uint8_t origin() const
    {
        return m_origin;
    }

    /*!
     * @brief This function returns a reference to member origin
     * @return Reference to member origin
     */
    eProsima_user_DllExport uint8_t& origin()
    {
        return m_origin;
    }


    /*!
     * @brief This function sets a value in member destination
     * @param _destination New value for member destination
     */
    eProsima_user_DllExport void destination(
            uint8_t _destination)
    {
        m_destination = _destination;
    }

    /*!
     * @brief This function returns the value of member destination
     * @return Value of member destination
     */
    eProsima_user_DllExport uint8_t destination() const
    {
        return m_destination;
    }

    /*!
     * @brief This function returns a reference to member destination
     * @return Reference to member destination
     */
    eProsima_user_DllExport uint8_t& destination()
    {
        return m_destination;
    }



private:

    std::string m_sender_id;
    uint8_t m_origin{0};
    uint8_t m_destination{0};

};

#endif // _FAST_DDS_GENERATED_EMERGENCYMSG_HPP_


